Mi commit
apaganobeleno/rodo-training-2 pull request #1
Opened 2016-11-22 21:35 UTC by rdiazrovira

Scans Client IP and displays Information IP

2016-11-22 21:42 UTC, paganotoni requested changes

2016-11-22 21:42 UTC, apaganobeleno commented on main.go
> +	http.HandleFunc("/ip/details", ipScanner.StartIPScan)
@rdiazrovira well done, i think you missed the part were you should handle non-existing routes with a json 404 response, could you implement it please ?

2016-11-22 21:48 UTC, rdiazrovira commented on main.go
> +	http.HandleFunc("/ip/details", ipScanner.StartIPScan)
Sure, I'll implement it.

2016-11-23 21:18 UTC, paganotoni approved these changes

2016-11-23 21:18 UTC, merged